# Generated by Django 4.1.4 on 2022-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
