# Generated by Django 4.1.4 on 2022-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
