# Generated by Django 4.1.4 on 2022-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
